# Generated by Django 5.1.7 on 2025-03-19 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('url_manager', '0002_redirectrule_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='redirectrule',
            name='redirect_identifier',
            field=models.CharField(default=1, editable=False, max_length=16, unique=True),
            preserve_default=False,
        ),
    ]
